### ISSUE TITLE
ResNet的表格有两处笔误吧

### ISSUE THREAD

**Issue by shanhaoli** [Ryanrenqian/AI_HW#1]
一个是`Conv2-x` 中的 `Output size` 应该是 56x56. 另一个是 `Conv5-x`的`channel`按规律应该是 512.

**Comment by Ryanrenqian** [comment]
![image](https://user-images.githubusercontent.com/8614325/66697284-b859f280-ed06-11e9-8d75-7f3ea3988d5c.png)

给你点赞

**Comment by MeowFET** [comment]
![image](https://user-images.githubusercontent.com/16898790/67206509-5c991300-f444-11e9-817d-889e5c29abdf.png)

Assignment 表格中，每个 conv*_x block 内，均有一层 3×3 max pool，与 ResNet 论文中 ResNet-18 不同。（论文中仅 conv2_x 的卷积层前有 pooling 层，其他 block 内 down-scale 通过 stride 2 的卷积层完成）

周一课间问了陈老师，老师表示应该按作业表格中的设计来构建网络，因此我已将网络改为上图的结构，重新训练。这里能否再次确认一下？非常感谢。

**Comment by Ryanrenqian** [comment]
作业的表格的设计是被TA（我）打错了的。。所以正确的是我在前面提到的那张图，你用的这张图让我有点费解你到底有没有使用正确的表格。

**Comment by MeowFET** [comment]
啊，被老师无意坑了 =-=
中间下课的时候我问陈老师，ResNet 论文中只有第一个 block 前面放了 pooling，表格里则每行都有，按哪个来。老师说，按表，我就哐哐一顿改。（把 stride 2 的卷积层变成 stride 1，然后加上 stride 2 的 3×3 pooling）
我再改回去重新训练吧😭，希望大家不要踩同样的坑。
