### ISSUE TITLE
关于resnet表格

### ISSUE THREAD

**Issue by R-JunmingChen** [Ryanrenqian/AI_HW#11]
一些疑问
1.  resnet论文里并没有在每一个block后面跟一个maxpool，只有第一层以及最后一层涉及到pooling
2.  最后是一个block resnet原本设计的size是512X512，但是表格中是256X256
3.  第一个block中的第一个conv 的kernel 数量6， 原本的设计应该是64

 这些与原始论文的不同点，是老师要求的设计吗，还是笔误，如果是笔误，能否更新表格

**Comment by Ryanrenqian** [comment]
请看最下面的issue(github已更新)
