### ISSUE TITLE
模型测试及作业的疑问

### ISSUE THREAD

**Issue by DoFulangChen** [Ryanrenqian/AI_HW#5]
1.按照PPT的Code Link，找到的Code不能直接跑通，line3显示.utils出现unsolved reference？后来改用python-utils，但后面的load_....哪里显示没有，如何解决？

2.urls给出的是训练好的模型，我们应该做的是写resnet18然后再训练吗？

**Comment by Ryanrenqian** [comment]
1。CodeLink：https://pytorch.org/docs/stable/_modules/torchvision/models/resnet.html
中对应的代码是封装在torch和torchvision包里面的，.util是torchvision里面的。尽管调用的util我们是用不到的因此，这里不能完全照搬源码，需要我们自己尝试搭建模型，此外，我们在搭建和修改模型的时候请标明引用出处，
2. 没错，我们是写好模型再重头训练的。
