### ISSUE TITLE
Feature mapping visualization

### ISSUE THREAD

**Issue by czhaneva** [Ryanrenqian/AI_HW#6]
I was confused about the section 2.8 Feature mapping visualization
The visualization means we just need to plot the feature mapping (batch, num_filter, 112, 112)
or we have to reconstructe the patterns (batch, num_filter, 224, 224)

**Comment by Ryanrenqian** [comment]
emmm, it`s a good question about our HW. So, now I would like to explains from google what the fearture mapping and reconstruction patterns .
1. The activation maps, called feature maps, capture the result of applying the filters to input, such as the input image or another feature map. The idea of visualizing a feature map for a specific input image would be to understand what features of the input are detected or preserved in the feature maps.
2. Reconstruction patterns are those that are primarily. used to reconstruct past events. □ Examples include blood spatter, glass fractures, fire. burn, and track and trail patterns.
And  I would like to provide u some knowledge of those problem. Hope I can help u
https://machinelearningmastery.com/how-to-visualize-filters-and-feature-maps-in-convolutional-neural-networks/

**Comment by flyyyyer** [comment]
Can we speak in Chinese?
在2.8 Feature mapping visualization中，我们只要可视化Conv1和Conv5_x的feature maps就行了吧。不用再可视化重构回的图片。
the reconstructed patterns from the validation set that cause high activations in a given feature map (2p).
the corresponding image patches for each feature map (2p).

就是不明白这2句话是干嘛的。

**Comment by R-JunmingChen** [comment]
https://machinelearningmastery.com/how-to-visualize-filters-and-feature-maps-in-convolutional-neural-networks/
This website doesn't mention the reconstructed patterns. 
Could you please tell us how can we find the exact definition cause there is no common definition and explanation for this term in deep learning. Is this term from some papers?

**Comment by flyyyyer** [comment]
2.8需要完成反卷积？Conv1，Conv5_x不仅要可视化feature maps，还要反卷积重构会输入图像？Conv5_x也要反回去？

**Comment by Ryanrenqian** [comment]
这里我问了陈杰老师,还没等到回复,等会儿上完课再去问问他

**Comment by flyyyyer** [comment]
> 这里我问了陈杰老师,还没等到回复,等会儿上完课再去问问他

有回复吗？

**Comment by Ryanrenqian** [comment]
后面两句话可能是这样来做的: https://mathpretty.com/10475.html
