### ISSUE TITLE
报告只写结果吗？

### ISSUE THREAD

**Issue by flyyyyer** [Ryanrenqian/AI_HW#7]
Report
Code for Task 2. The code should be based on Pytorch(Version 1.3 is required) platform and using python language. The results, curves and filter visualization are suggested to include in report.
Feedback
Your code should be bug free. You would get zero point if there are bugs and we can not run your code to get the results.

在报告里要附上代码吗？还是只写结果就行了

**Comment by Ryanrenqian** [comment]
report只用写结果，code和report一起打包压缩。
