### ISSUE TITLE
关于可视化

### ISSUE THREAD

**Issue by KeyaoLi10** [Ryanrenqian/AI_HW#8]
feature map 是指那个layer输出的图片吗还是卷积核的图片？
另外能不能解释下 I want both: 那个地方，没太看懂

**Comment by shanhaoli** [comment]
`feature map` 是指 `layer` 输出的 `tensor`，当然你可以理解为图片。

>  - I want both: 
>    - the reconstructed patterns from the validation set that cause high activations in a given feature map (2p).
>    - the corresponding image patches for each feature map (2p).

建议你看一下周围附上的链接，上面有讲到这个。（但这部分我也不还懂）

**Comment by flyyyyer** [comment]
群里有人提问最后一层可视化，是个点。请问不是7*7吗？

**Comment by Ryanrenqian** [comment]
feature map最后一层是一个点哟(已经有部分同学做出来,但助教还没开始做), 所以这里就有一点点问题了, 你需要一点点的trick,比如说resize图像之类的(陈老师提起过).  这里确实需要一些想法. 具体怎么做是对的我也不知道...

**Comment by flyyyyer** [comment]
![image](https://user-images.githubusercontent.com/56632276/66997000-41589b80-f104-11e9-84cb-81a7fa7c53c2.png)
为什么是一个点，Conv5-x出来是7×7呀，average pool出来之后才是1×1

**Comment by WangHelin1997** [comment]
> ![image](https://user-images.githubusercontent.com/56632276/66997000-41589b80-f104-11e9-84cb-81a7fa7c53c2.png)
> 为什么是一个点，Conv5-x出来是7×7呀，average pool出来之后才是1×1

这个图例貌似输入是224x224的，这样输出的确是7x7。如果采用原始图片32x32作为输入，那么Conv5-x输出就是1x1。

**Comment by flyyyyer** [comment]
好的，谢谢。
我就是输入resize到224x224的。题目也没说拿32×32作为输入，按照题目给出的Table 1 your own ResNet model，我第一感觉就是用224x224作为输入。
