### ISSUE TITLE
The network structure does not match CIFAR-10

### ISSUE THREAD

**Issue by ChongZhangZC** [Ryanrenqian/AI_HW#9]
CIFAR-10  consists of 32x32 colour images. The output size is {112, 56, 28, 7}. I think resizing 32 x 32 to  224 x 224 has a negative impact on recognition.
The Network for CIFAR-10 in ResNet Paper is as follows

The network inputs are 32x32 images, with the per-pixel mean subtracted. The first layer is 3x3 convolutions. Then we use a stack of 6n layers with 3x3 convolutions on the feature maps of sizes {32; 16; 8} respectively, with 2n layers for each feature map size. The numbers of filters are {16; 32; 64} respectively. The subsampling is performed by convolutions with a stride of 2. The network ends with a global average pooling, a 10-way fully-connected layer, and softmax. There are totally 6n+2 stacked weighted layers. The following table summarizes the architecture:
![RI{ 4 95Z 9PGM@180Z 28](https://user-images.githubusercontent.com/26456963/66983703-c4b9c300-f0eb-11e9-9b04-f47f1d7fa238.png)

**Comment by Ryanrenqian** [comment]
As u said, resizing image from 32x32 to 224x224 might be a terrible idea. However, have u ever tested this method?  The aim of this homework is not only coding but also critical thinking. 
Hope your experiments would give other classmates some useful information of this homework.
PS. prof. Chen has mentioned resizing method, what do u think about it?
